### ISSUE TITLE
[parcel-sourcemap] Source out of range

### ISSUE THREAD

**Issue by marcelkorpel** [HellButcher/parcel-transformer-svelte3-plus#1]
When trying to build [this minimal example](https://github.com/marcelkorpel/svelte-parcel-test) (using `npm run dev`), I get the following error:
```
🚨 Build failed.

parcel-transformer-svelte3-plus: [parcel-sourcemap] Source out of range

  Error: [parcel-sourcemap] Source out of range
  at NodeSourceMap.addVLQMap (/Users/marcel/Sites/sveltest/node_modules/@parcel/source-map/dist/node.js:37:28)
  at extendSourceMap (/Users/marcel/Sites/sveltest/node_modules/parcel-transformer-svelte3-plus/index.js:27:7)
  at Object.transform (/Users/marcel/Sites/sveltest/node_modules/parcel-transformer-svelte3-plus/index.js:214:14)
  at async Transformation.runTransformer (/Users/marcel/Sites/sveltest/node_modules/@parcel/core/lib/Transformation.js:627:5)
  at async Transformation.runPipeline (/Users/marcel/Sites/sveltest/node_modules/@parcel/core/lib/Transformation.js:376:36)
  at async Transformation.runPipelines (/Users/marcel/Sites/sveltest/node_modules/@parcel/core/lib/Transformation.js:253:40)
  at async Transformation.run (/Users/marcel/Sites/sveltest/node_modules/@parcel/core/lib/Transformation.js:173:21)
  at async Child.handleRequest (/Users/marcel/Sites/sveltest/node_modules/@parcel/workers/lib/child.js:217:9)
```
The problem disappears when I remove the `import` of Nested.svelte in assets/src/App.svelte (and the corresponding `<Nested/>` tag), so this is somehow what triggers the error.

**Comment by HellButcher** [comment]
The problem also disappears when using the `parcel build` command (not the serve or watch subcommand)

**Comment by marcelkorpel** [comment]
Thanks, but this way there are no source maps written, so I can't add breakpoints and the like in the browser's developer tools, can I?

**Comment by HellButcher** [comment]
I have reverted the last change, BUT now, the relative path to the original source us used.
I hope the SorceMaps are working properly now.

**Comment by marcelkorpel** [comment]
Alas, the same error as above, after updating to 0.2.5.

**Comment by HellButcher** [comment]
Ok, found out, that I probably had outdated versions inside my node_modules.
After updating, I was able to repsoduce this again.

I probably found the root-cause: The SourceMap of the preprocessed `scss` includes *two* paths to source-files: an absolute path, and a relative path to the same Nested.svelte file (only when not building a production-build). 
These paths are now rebased to the project-root.
